version: "3.9"
services:
  dqApi:
    image: maschinee/flat-bachelor-api:latest
    ports:
      - "8099:8099"
    environment:
      - SPRING_DATA_MONGODB_AUTHENTICATION_DATABASE=admin
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=root
      - SPRING_DATA_MONGODB_PASSWORD=example
      - SPRING_DATA_MONGODB_DATABASE=dqualizer
    healthcheck:
      test: wget --no-verbose --tries=1 --spider localhost:8099/actuator/health || exit 1
      interval: 60s
      start_period: 5s
      retries: 5
      timeout: 10s

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - data:/data
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  dqanalyzer-react:
    image: maschinee/flat-bachelor-react:latest
    ports:
      - "9090:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:8099
    depends_on:
      dqApi:
        condition: service_healthy

volumes:
  data: {}
